apiVersion: v1
data:
  core-site.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<?xml-stylesheet
    type=\"text/xsl\" href=\"configuration.xsl\"?>\n<configuration>\n    <property>\n
    \       <name>fs.s3a.connection.ssl.enabled</name>\n        <value>false</value>\n
    \   </property>\n\n    <property>\n        <name>fs.s3a.endpoint</name>\n\t<value>http://minio-api.openshift-operators.svc.cluster.local:9000</value>\n
    \   </property>\n\n    <property>\n        <name>fs.s3a.access.key</name>\n        <value>minioadmin</value>\n
    \   </property>\n\n    <property>\n        <name>fs.s3a.secret.key</name>\n        <value>minioadmin</value>\n
    \   </property>\n\n    <property>\n        <name>fs.s3a.path.style.access</name>\n
    \       <value>true</value>\n    </property>\n\n    <property>\n        <name>fs.s3a.impl</name>\n
    \       <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>\n    </property>\n</configuration>\n\n"
  hive-site.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<?xml-stylesheet
    type=\"text/xsl\" href=\"configuration.xsl\"?>\n<configuration>\n    <property>\n
    \       <name>hive.metastore.local</name>\n        <value>false</value>\n    </property>\n
    \   <property>\n        <name>javax.jdo.option.ConnectionURL</name>\n        <value>jdbc:postgresql://postgres-hms:5432/metastore</value>\n
    \   </property>\n    <property>\n        <name>javax.jdo.option.ConnectionDriverName</name>\n
    \       <value>org.postgresql.Driver</value>\n    </property>\n    <property>\n
    \       <name>javax.jdo.option.ConnectionUserName</name>\n        <value>hive</value>\n
    \   </property>\n    <property>\n        <name>javax.jdo.option.ConnectionPassword</name>\n
    \       <value>hive</value>\n    </property>\n    <property>\n        <name>fs.s3a.connection.ssl.enabled</name>\n
    \       <value>false</value>\n    </property>\n    <property>\n\t<name>fs.s3a.endpoint</name>\n\t<value>http://minio-api.openshift-operators.svc.cluster.local:9000</value>\n
    \   </property>\n    <property>\n       <name>fs.s3a.access.key</name>\n       <value>minioadmin</value>\n
    \   </property>\n    <property>\n       <name>fs.s3a.secret.key</name>\n       <value>minioadmin</value>\n
    \   </property>\n    <property>\n      <name>fs.s3a.path.style.access</name>\n
    \     <value>true</value>\n    </property>\n    <property>\n        <name>fs.s3a.impl</name>\n
    \       <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>\n    </property>\n
    \   <property>\n        <name>metastore.thrift.uris</name>\n        <value>thrift://hive-hms:9083</value>\n
    \   </property>\n    <property>\n      <name>hive.metastore.warehouse.dir</name>\n
    \     <value>s3a://hive/warehouse</value>\n    </property>\n</configuration>\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: hive-hms-config
